input-datastore:
    Download-Source:
        type: "Tweepy"
        config: ~
inout-datastore:
    Cluster:
        type: "Mongo"
        config:
            location: "mongodb://localhost:27017"
            datastore-name: "Data"
            collection-name: "Clusters"
    LocalNeighbourhood:
        type: "Mongo"
        config:
            location: "mongodb://localhost:27017"
            datastore-name: "Data"
            collection-name: "LocalNeighbourhoods"
    ProcessedTweet:
        type: "Mongo"
        config:
            location: "mongodb://localhost:27017"
            datastore-name: "Data"
            collection-name: "ProcessedTweet"
    Ranking:
        type: "Mongo"
        config:
            location: "mongodb://localhost:27017"
            datastore-name: "Data"
            collection-name: "Rankings"
    UserTweet:
        type: "Mongo"
        config:
            location: "mongodb://localhost:27017"
            datastore-name: "Data"
            collection-name: "UserTweets"
    SocialGraph:
        type: "Mongo"
        config:
            location: "mongodb://localhost:27017"
            datastore-name: "Data"
            collection-name: "SocialGraphs"
    Users:
        type: "Mongo"
        config:
            location: "mongodb://localhost:27017"
            datastore-name: "Data"
            collection-name: "Users"
    Friends:
        type: "Mongo"
        config:
            location: "mongodb://localhost:27017"
            datastore-name: "Data"
            collection-name: "Friends"
    CleanedFriends:
        type: "Mongo"
        config:
            location: "mongodb://localhost:27017"
            datastore-name: "Data"
            collection-name: "CleanedFriends"
    UserWordFrequency:
        type: "Mongo"
        config:
            location: "mongodb://localhost:27017"
            datastore-name: "Data"
            collection-name: "UserWordFrequency"
    UserRelativeWordFrequency:
        type: "Mongo"
        config:
            location: "mongodb://localhost:27017"
            datastore-name: "Data"
            collection-name: "UserRelativeWordFrequency"
    ClusterWordFrequency:
        type: "Mongo"
        config:
            location: "mongodb://localhost:27017"
            datastore-name: "Data"
            collection-name: "ClusterWordFrequency"
    ClusterRelativeWordFrequency:
        type: "Mongo"
        config:
            location: "mongodb://localhost:27017"
            datastore-name: "Data"
            collection-name: "ClusterRelativeWordFrequency"
    GlobalWordFrequency:
        type: "Mongo"
        config:
            location: "mongodb://localhost:27017"
            datastore-name: "Data"
            collection-name: "GlobalWordFrequency"
    UserLikedTweet:
        type: "Mongo"
        config:
            location: "mongodb://localhost:27017"
            datastore-name: "Data"
            collection-name: "UserLikedTweet"
    UserLikedTweetIndicator:
        type: "Mongo"
        config:
            location: "mongodb://localhost:27017"
            datastore-name: "Data"
            collection-name: "UserLikedTweetIndicator"
